---
 - name: "Ansible Create user"
   hosts: web
   tasks:
     - name: "Add the user 'user1' with a specific uid and a primary group of 'sudo'"
       ansible.builtin.user:
         name: user1
         group: sudo
         password: '$6$kjPn3KClxO.Lujw$BjDr2y4vvJK3Q.C/nLET.A/FD9OxN6DNASmLetapq9LiXVVlTrYnvlEGuITZiVkV3JhX.vbsZ68/hnbdRsYnx1'
         createhome: yes     # Defaults to yes
         home: /home/user1    # Defaults to /home/<username>

 - name: "Ansible SSH functionlity module demo"
   hosts: web
     # Defining the remote server where the ansible create user module will manage the objects
   remote_user: ubuntu   # Using Remote user as ubuntu
   tasks:
     # Creating the SSH key for the user1 in .ssh directory
     - name: "Create a 2048-bit SSH key for user1 in ~user1/.ssh/id_rsa"
       ansible.builtin.user:
         name: user1
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: ~/.ssh/id_rsa