---
- hosts: app
  become: yes
  tasks:
    - name: Adding docker repo CentOS 8
      shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_distribution == "CentOS"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == "Debian"

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_distribution == "Debian"

    - name: "Install docker"
      package:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  ......


- name: "Running docker"
  service:
    name: docker
    state: started

- hosts: database
  become: yes..
  tasks:

    - debug: msg="play_hosts={{play_hosts}}"
    - debug: msg="ansible_distribution={{ansible_distribution}}"
  .
- name: postgresql key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true
  .....
- name: create variable
  command: bash -c "echo \"deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main\" "
  register: repo_line
  .
- debug:.
  msg: "{{ repo_line.stdout }}"
  .......
- name: add postgresql repo.
  apt_repository:
    repo: "{{ repo_line.stdout }}"
    state: present
  become: true
  .
- name: install postgresql
  apt:
    name: "postgresql-{{postgresql_version}}"
    state: present
    update_cache: yes
  become: true
