---
- hosts: "localhost"
  connection: "local"
  vars:
    users:
      - "newuser1"
      - "newuser2"
  tasks:
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
        groups: "admin,www-data"
      with_items: "{{ users }}"
    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
      with_items: "{{ users }}"